# Generated by Django 5.2 on 2025-04-15 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='property',
            new_name='real_property',
        ),
    ]
