# Generated by Django 5.2 on 2025-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0003_area_property_image_property_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='share_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='investment',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_shares',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='shares_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
