# Generated by Django 5.2 on 2025-04-16 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ownership', '0004_alter_certificate_share_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='share_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='real_property',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='shares_purchased',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default=3809, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='property',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='ownership.property'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='shares_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='processing', max_length=20),
        ),
    ]
