# Generated by Django 5.2.8 on 2025-11-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ownership", "0005_rename_transaction_date_transaction_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="price_per_share",
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
